[template]
src = "haproxy.cfg.tmpl"
dest = "/etc/haproxy/haproxy.cfg"
keys = [
        "/clusterstate/cruwe_de"
]
check_cmd = "echo checking && haproxy -c -f {{ .src }}"
reload_cmd = "echo reloading && haproxy -f /etc/haproxy/haproxy.cfg -p /var/run/haproxy.pid -st $(cat /var/run/haproxy.pid)"
